# Generated by Django 2.1.4 on 2019-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
