# Generated by Django 2.1.4 on 2019-04-08 15:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0002_auto_20190404_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time_slot', models.CharField(choices=[('morning_first', '12h00'), ('morning_second', '13h00'), ('morning_third', '14h00'), ('morning_fourth', '15h00'), ('evening_first', '20h00'), ('evening_second', '21h00'), ('evening_third', '22h00')], max_length=15)),
                ('num_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forkilla.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ViewedRestaurants',
            fields=[
                ('id_vr', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant', models.ManyToManyField(to='forkilla.Restaurant')),
            ],
        ),
    ]
