# Generated by Django 2.1.4 on 2019-04-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0003_reservation_viewedrestaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_id', models.CharField(max_length=10, unique=True)),
                ('restaurant_number', models.CharField(max_length=8)),
                ('message', models.TextField()),
                ('review_stars', models.PositiveIntegerField()),
            ],
        ),
    ]
