# Generated by Django 2.1.4 on 2019-05-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous User', max_length=200),
        ),
    ]
