# Generated by Django 2.1.4 on 2019-05-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0006_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
