# Generated by Django 2.1.4 on 2019-05-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0007_remove_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comment',
        ),
    ]
