# Generated by Django 2.1.4 on 2019-05-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0007_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInsertDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.Restaurant')),
                ('viewedrestaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.ViewedRestaurants')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
