# Generated by Django 2.1.4 on 2019-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrestaurant',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrestaurant',
            name='user',
            field=models.CharField(default='Anonymous User', max_length=200),
        ),
    ]
