# Generated by Django 2.1.4 on 2019-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0006_auto_20190512_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.CharField(default='Anonymous User', max_length=200),
        ),
    ]
