# Generated by Django 2.1.4 on 2019-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0010_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('comercial', 'comercial'), ('admin', 'admin'), ('client', 'client')], max_length=15),
        ),
    ]
